# Generated by Django 4.0.6 on 2022-08-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('detalhes', models.CharField(max_length=200)),
                ('tecnologias', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
