# Generated by Django 4.0.6 on 2022-08-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projeto',
            table='projetos',
        ),
    ]
