# Generated by Django 4.0.6 on 2022-08-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.TextField(max_length=200),
        ),
    ]
