# Generated by Django 4.0.6 on 2022-07-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('conteudo', models.TextField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
