# Generated by Django 4.0.6 on 2022-08-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
